export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const CART_ITEM_QUANTITY_UPDATE = 'CART_ITEM_QUANTITY_UPDATE';
export const CART_ITEM_QUANTITY_FAILURE = 'CART_ITEM_QUANTITY_FAILURE';
